portfolio_project/urls.py
# portfolio_project/urls.py

from django.contrib import admin
from django.urls import path
from portfolio import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/models.py
# portfolio/models.py

from django.db import models

class Contact(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    about_project = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.name} - {self.email}"
    
    
class Project(models.Model):
    title = models.CharField(max_length=100)
    url = models.URLField(max_length=200)
    upload = models.ImageField() 
    description = models.CharField(max_length=1000)
    
    def __str__(self):
        return self.title
    

portfolio/forms.py
# # portfolio/forms.py

# from django import forms
# from .models import Contact

# class ContactForm(forms.ModelForm):
#     class Meta:
#         model = Contact
#         fields = ['name', 'email', 'about_project']
#         widgets = {
#             'name': forms.TextInput(attrs={'placeholder': 'Your Name'}),
#             'email': forms.EmailInput(attrs={'placeholder': 'Your Email'}),
#             'about_project': forms.Textarea(attrs={'placeholder': 'About Project'}),
#         }


from django import forms
from .models import Contact

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ['name', 'email', 'about_project']
        widgets = {
            'name': forms.TextInput(attrs={'placeholder': ' ', 'class': 'form-control name-input'}),
            'email': forms.EmailInput(attrs={'placeholder': ' ', 'class': 'form-control email-input'}),
            'about_project': forms.Textarea(attrs={'placeholder': ' ', 'class': 'form-control project-textarea'}),
        }

portfolio/views.py
# portfolio/views.py

from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import ContactForm
from .models import Contact, Project

def index(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your message has been sent successfully!')
            return redirect('index')
    else:
        form = ContactForm()


    context = {
        'form': form,
        'projects' : Project.objects.all()
	}

   
    return render(request, 'index.html', context)

portfolio/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{% static '/favicon.png' %}" type="image/x-icon">
    <title>UI/UX | Aalok Bista</title>  
    {% load static %}
    <link rel="stylesheet" href="{% static 'portfolio/css/style.css' %}">
</head>
<body>
    {% block content %}
    {% endblock %}
</body>
</html>

portfolio/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container" id="home">
    <header>
        <nav>
            <ul>
                <li><a href="#home">
                    <img src="{% static 'home.png' %}" alt="Cover Photo" class="icon">
                </a></li>
                <li><a href="#projects">Projects</a></li>
                <li><a href="#contact">Contact me</a></li>
            </ul>
        </nav>
    </header>

    <section id="about">
        <div class="hero">
            <h1 class="tagline">Hi, I am Aalok,<br>UX/UI Designer</h1>
            <p class="description">I'm a UX/UI Designer passionate about participating in all stages of the digital
                product, from discovery to delivery. Helping to focus business goals on users.</p>
            <a href="#contact" class="btn">Contact Me</a>
        </div>
        <div class="hero-img">
            <img src="{% static 'photo.png' %}" alt="Cover Photo" class="cover-photo">
        </div>
    </section>

    <section id="projects">
        <h2>Featured Projects</h2>
        <p>There's more on behance!</p>
        <div class="project-grid">
            {% for project in projects %}
            <div class="project-card">
                <img src="{{ project.upload.url }}" alt="{{ project.title }}">
                <div class="project-detail">
                    <h3>{{ project.title }}</h3>
                    <a href="{{ project.url }}" target="_blank" class="card-btn">Behance</a>
                </div>
            </div>
            {% endfor %}
        </div>
    </section>

    <section id="skills">
        <h2>Skills</h2>
        <ul>
            <div class="skill-item one">
                <img src="{% static '1.png' %}" alt="User Research" class="icon">
                <li>User Research</li>
            </div>
            <div class="skill-item two">
                <img src="{% static '1.png' %}" alt="Wireframing" class="icon">
                <li>Wireframing</li>
            </div>
            <div class="skill-item three">
                <img src="{% static '1.png' %}" alt="UI/UX Designing" class="icon">
                <li>UI/UX Designing</li>
            </div>
            <div class="skill-item four">
                <img src="{% static '1.png' %}" alt="Prototyping" class="icon">
                <li>Prototyping</li>
            </div>
            <div class="skill-item five">
                <img src="{% static '1.png' %}" alt="UI Designing" class="icon">
                <li>UI Designing</li>
            </div>
        </ul>
    </section>

    <section id="contact">
        <div class="form-info">
            <h2>Contact Here</h2>
            <p> 
            Have a project idea?<br> just say me <strong>Hi</strong>.
            </p>
            <img src="{% static 'arrow.png' %}" alt="Arrow">
            <div class="socials">
                <a href="#" target="_blank"><img src="{% static 'facebook.png' %}" alt="Facebook"></a>
                <a href="https://www.behance.net/aalokbista1" target="_blank"><img src="{% static 'behance.png' %}" alt="Behance"></a>
                <a href="#" target="_blank"><img src="{% static 'twitter.png' %}" alt="Twitter"></a>
                <a href="https://www.instagram.com/aalokdesigns/" target="_blank"><img src="{% static 'instagram.png' %}" alt="Instagram"></a>
                <a href="https://www.linkedin.com/in/aalokbista/" target="_blank"><img src="{% static 'linkedin.png' %}" alt="LinkedIn"></a>
                <a href="https://dribbble.com/aalokbista" target="_blank"><img src="{% static 'dribble.png' %}" alt="Dribble" style="color: black;"></a>
            </div>
        </div>

        <div class="form-field">
            <form method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_name">Name</label>
                    {{ form.name }}
                </div>
                <div class="form-group">
                    <label for="id_email">Your Email</label>
                    {{ form.email }}
                </div>
                <div class="form-group">
                    <label for="id_about_project">About Project</label>
                    {{ form.about_project }}
                </div>
                <button type="submit" class="submit-btn">Submit</button>
            </form>
        </div>
    </section>

    <footer>
        <p>Copyright ©2024 All rights reserved</p>
    </footer>
</div>
{% endblock %}